export { makeProductRepository } from './infrastructure/productRepository'
export { makeListProducts } from './application/listProducts'
export { makeListCategories } from './application/listCategories'
export { makeProductsRouter } from './presentation/productRoutes'
export { makeGetProduct } from './application/getProduct'
export { makeListProductsForSitemap } from './application/listProductsForSitemap'
