export interface Review {
  id: number
  text: string
  name: string
  country: string
  rating: number
}
 
export const REVIEWS: Review[] = [
  {
    id: 1,
    text: 'This is the cutest little figurine of a unicorn I have ever seen. I love it. This unicorn figurine is well made. It also matches the description on the Etsy web page and meets my expectations.',
    name: 'Annie Davey',
    country: 'United States',
    rating: 5,
  },
  {
    id: 2,
    text: 'Excellent service from the seller. So lovely and cute. Was just how I wanted it Would definitely recommend this seller.',
    name: 'charlotte Bassett',
    country: 'Germany',
    rating: 5,
  },
  {
    id: 4,
    text: 'This is adorable, can\'t wait to add it to my gift!',
    name: 'Nicola Joyner',
    country: 'United States',
    rating: 5,
  },
  {
    id: 6,
    text: 'There was a little mix up on the message card, but the seller quickly fixed it and sent me a new card and ribbon at no charge. Wife absolutely loved it.',
    name: 'Mike',
    country: 'United States',
    rating: 5,
  },
  {
    id: 7,
    text: 'What a wonderful gift. It is incredibly cute. The little bean looks as good in person as it does in the photos.',
    name: 'Curtis',
    country: 'France',
    rating: 5,
  },
  {
    id: 8,
    text: 'this is so cute and just what i wanted thanks!',
    name: 'Zahava',
    country: 'United States',
    rating: 5,
  },
  {
    id: 10,
    text: 'I got this for a friend’s birthday gift and she hasn’t opened it yet but omg it’s so cute!!! I’m sure she’s gonna love it!',
    name: 'Cami',
    country: 'Netherlands',
    rating: 5,
  },
  {
    id: 11,
    text: 'My boyfriend and I call each other "bean" so this was a very cute gift we both enjoyed!!',
    name: 'Stephanie',
    country: 'United States',
    rating: 5,
  },
  {
    id: 12,
    text: 'Absolutely perfect! Well-crafted and was as cute as a button! Really appreciated the swiftness of shipping and the care in packaging.',
    name: 'Jennie Davis',
    country: 'Australia',
    rating: 5,
  },
  {
    id: 13,
    text: 'They are so cute! And they hang off the cup perfectly! Thank you so much for the custom order, I know my Mother-in-law is going to love hers too.',
    name: 'Sara Hartsell',
    country: 'United States',
    rating: 5,
  },
  {
    id: 14,
    text: 'Precious item. Gave to a friend who is my other “p”.',
    name: 'Susan Shinbara',
    country: 'Belgium',
    rating: 5,
  },
  {
    id: 15,
    text: 'This arrived exactly like the picture. I was really impressed with the quality of the tiniest details!',
    name: 'Lyndsey Winters',
    country: 'United States',
    rating: 5,
  },
  {
    id: 18,
    text: 'Sehr süss gemacht, sieht im Original genau gleich aus wie auf den Bildern. Schnelle Lieferung, schöne Verpackung, Beschriftung klappt tiptop.',
    name: 'Jacqueline',
    country: 'Germany',
    rating: 5,
  },
  {
    id: 21,
    text: 'looks exactly as pictured. got it as a gift for my boss and I ordered late so it got here late but he absolutely loves it',
    name: 'Andrea S',
    country: 'United States',
    rating: 5,
  },
  {
    id: 26,
    text: 'Nat was super responsive and the little gifts I got for my coworkers were perfect, good quality and shipped carefully. Highly recommend!',
    name: 'Diana Lee',
    country: 'South Korea',
    rating: 5,
  },
  {
    id: 27,
    text: 'this is absolutely perfect and just as advertised! shipping was wonderful coming internationally! seller was very helpful and quick to respond. excited to give this to our drum instructor.',
    name: 'jena Schulz',
    country: 'Germany',
    rating: 5,
  },
  {
    id: 28,
    text: 'exactly as pictured and came in a super cute gift box',
    name: 'Sarah McMahon',
    country: 'Ireland',
    rating: 5,
  },
  {
    id: 29,
    text: 'Super cadeau ! Je l\'ai offert à ma meilleure amie et elle a adoré !!',
    name: 'Quentin Jordannet',
    country: 'France',
    rating: 5,
  },
  {
    id: 30,
    text: 'It’s the smallest, cutest unicorn there ever was! 💜 I knew that shipping would take a while and that was fine; it actually arrived sooner than I expected, which was nice. It is beautifully packaged in a cute tiny box.',
    name: 'Liz',
    country: 'United States',
    rating: 5,
  },
  {
    id: 31,
    text: 'Oh my gosh I love this so much! I don\'t want to gift it to my niece for her Christmas present! <:\'(',
    name: 'Danielle Edwards',
    country: 'Netherlands',
    rating: 5,
  },
  {
    id: 32,
    text: 'Very cute and just a pictured. Exactly what I expected',
    name: 'Caroline',
    country: 'United States',
    rating: 5,
  },
  {
    id: 33,
    text: 'Packaged with care, and even cuter in person! 💕💝the perfect gift 😁',
    name: 'Sawyer Wisniewski',
    country: 'Poland',
    rating: 5,
  },
  {
    id: 34,
    text: 'Great service and great quality product! Will definitely be back!',
    name: 'Jessica Jarrell',
    country: 'Australia',
    rating: 5,
  },
  {
    id: 35,
    text: 'Cute little spin on words The gift box was perfect as well that is comes in',
    name: 'Jenifer Teel',
    country: 'United States',
    rating: 5,
  },
  {
    id: 36,
    text: 'Natalia was super responsive and the little gifts for my team were so adorable. They even arrived early and in perfect condition. Highly recommend as a cute small gift for others!',
    name: 'Diana Lee',
    country: 'South Korea',
    rating: 5,
  },
  {
    id: 37,
    text: 'The person who received this gift thought it was super cute! Shipping was timely & I’m pleased! Thanks!',
    name: 'S P',
    country: 'Belgium',
    rating: 5,
  },
  {
    id: 39,
    text: 'I love it, I can\'t wait to give it to my boyfriend he is absolutely going to love it!!!',
    name: 'Mark Bennett',
    country: 'United States',
    rating: 5,
  },
  {
    id: 43,
    text: 'Wonderfully cute little bottles. Shipping was fast and Seller was very helpfull.',
    name: 'Florian',
    country: 'United States',
    rating: 5,
  },
  {
    id: 48,
    text: 'A magnificent piece of art from an extremely talented artist. I could not be happier!',
    name: 'Jen Kahn',
    country: 'United Kingdom',
    rating: 5,
  },
  {
    id: 49,
    text: 'Beautiful piece! It was also packaged so carefully and sweet. Fast seller response and shipping!! Highly recommend',
    name: 'Becky',
    country: 'United States',
    rating: 5,
  },
  {
    id: 50,
    text: 'This was a fun gift for a music teacher. She loved it!',
    name: 'Chelsea',
    country: 'France',
    rating: 5,
  },
  {
    id: 51,
    text: 'Brilliant. After having the first order being lost in the mail the sell issued a full refund without me asking. Second order arrived just fine. Excellent service and great seller',
    name: 'Tristan Burman',
    country: 'United States',
    rating: 5,
  },
  {
    id: 57,
    text: 'So beautiful looks amazing very happy with it and how it arrived!!',
    name: 'Nicole',
    country: 'United States',
    rating: 5,
  },
  {
    id: 61,
    text: 'mailed to a friend and they never received product. not due to shop, but due to usps. shop owner was friendly and responsive.',
    name: 'Emerald',
    country: 'Belgium',
    rating: 5,
  },
  {
    id: 62,
    text: 'Adorable! Sent to a friend and it made their day.',
    name: 'Larissa Fogelman',
    country: 'United States',
    rating: 4,
  },
  {
    id: 63,
    text: 'Got this for my bf and another one also for his bday. He thought they were cute and asked where I got them.',
    name: 'Jessica Hamilton',
    country: 'Cyprus',
    rating: 5,
  },
  {
    id: 64,
    text: 'These little buddies are beyond adorable and perfect. I am keeping one for myself and the other two I\'m gifting 🙂',
    name: 'Marlena Sniadajewski',
    country: 'Poland',
    rating: 5,
  },
  {
    id: 65,
    text: 'I got this for my fiance as a fun pick-me-up gift, and he loved it. It\'s super cute, tiny, and I love that you can actually remove the raspberry if you want (versus it being glued in). Super happy with the purchase!',
    name: 'Lisa Pelikan',
    country: 'United States',
    rating: 5,
  },
  {
    id: 66,
    text: 'this charm is super cute!! the bees got a little jumbled in shipping but I was able to right them with a pair of tweezers.',
    name: 'Jess Flake',
    country: 'Germany',
    rating: 5,
  },
  {
    id: 67,
    text: 'It’s so incredibly cute!!! I’m so happy I found it! Amazing quality and such cute wrapping paper! It will be such a cute gift!',
    name: 'Alyssa',
    country: 'United States',
    rating: 5,
  },
  {
    id: 68,
    text: 'Item is great quality and was exactly what I was expecting. It is adorable! My boyfriend loves it!',
    name: 'Robin Wyman',
    country: 'United Kingdom',
    rating: 5,
  },
  {
    id: 69,
    text: 'The figurine looks just as expected. Natalya was also super helpful, thank you!',
    name: 'Tamara',
    country: 'United States',
    rating: 5,
  },
  {
    id: 70,
    text: 'Item was unfortunately lost in the mail. Seller was quick to respond to all messages and even issued a full refund completely unprompted after less than 2 weeks of getting no updates from the post offices. I have ordered another one of these as soon as I got the refund partly because of just how much help the seller was in tackeling this issue.',
    name: 'Tristan Burman',
    country: 'France',
    rating: 5,
  },
  {
    id: 71,
    text: 'They look amazing! Shipped carefully and even included a little gift. Thank you so much!',
    name: 'White Oak Apiaries',
    country: 'United States',
    rating: 5,
  },
  {
    id: 72,
    text: 'This is so adorable! I am obsessed and I can’t wait to give this to my boyfriend for Christmas!',
    name: 'Suzy Bee',
    country: 'Netherlands',
    rating: 5,
  },
  {
    id: 73,
    text: 'This is too cute and I can’t wait to give it to my coworker!! She’s going to love it',
    name: 'Suzy Bee',
    country: 'United States',
    rating: 5,
  },
  {
    id: 74,
    text: 'My coworker makes these amazing cupcakes and this is the best gift for her! I can’t wait for her to see this!',
    name: 'Suzy Bee',
    country: 'Australia',
    rating: 5,
  },
  {
    id: 75,
    text: 'This is too cute to pass up! I can’t wait to gift it to my friend for Halloween!!',
    name: 'Suzy Bee',
    country: 'United States',
    rating: 5,
  },
  {
    id: 76,
    text: 'so I bought this lil gift for my boyfriend. it came in and I love it! can\'t wait for my boyfriend to come home so he can see it too! definitely buying more so I can give them to my management team at work! they are too cute!',
    name: 'Victoria Langley',
    country: 'Belgium',
    rating: 5,
  },
  {
    id: 77,
    text: 'This is absolutely precious. I can\'t wait to give this to my daughter for her birthday!',
    name: 'Sara Roseman',
    country: 'United States',
    rating: 5,
  },
  {
    id: 80,
    text: 'This is absolutely precious. I can\'t wait to give this to my son for Christmas!',
    name: 'Sara Roseman',
    country: 'Germany',
    rating: 5,
  },
  {
    id: 81,
    text: 'So sweet! Unfortunately the glass tube was completely shattered on arrival but I quickly found a replacement. Thank you! :)',
    name: 'Parker',
    country: 'United States',
    rating: 5,
  },
  {
    id: 86,
    text: 'I adore my lucky stars!! They are true to the photo, beautifully made. I will definitely be purchasing more from this artist. Thank you!',
    name: 'Emilia Lucania',
    country: 'Netherlands',
    rating: 5,
  },
  {
    id: 88,
    text: 'Love the detail on these, and they come carefully packaged with additional bubble wrap in the jar. So cute!',
    name: 'Grace',
    country: 'United States',
    rating: 5,
  },
  {
    id: 89,
    text: 'Shipped and arrived fast, considering it came from overseas. Looks just like the picture, and the little smile is too cute.',
    name: 'Grace',
    country: 'Australia',
    rating: 5,
  },
  {
    id: 90,
    text: 'I appreciate that my heart that I received is very \'heart\' shaped and looks exactly like the photos, as it is going to be a gift! Thank you :) I will be returning for future purchases',
    name: 'Grace',
    country: 'United States',
    rating: 5,
  },
  {
    id: 91,
    text: 'Beautiful! I have purchased a few of your items and will be returning again. Thanks.',
    name: 'Mynyddoedd',
    country: 'Belgium',
    rating: 5,
  },
  {
    id: 92,
    text: 'Adorable! Well made and as expected. I can\'t wait to see more.',
    name: 'Pamela Eastwood',
    country: 'United States',
    rating: 5,
  },
  {
    id: 93,
    text: 'Absolutely perfect and adorable and I can\'t wait to gift it to my daughter!',
    name: 'Tracie',
    country: 'Cyprus',
    rating: 5,
  },
  {
    id: 94,
    text: 'So adorable! Gave to my boyfriend with his birthday gift and he loved it. Great quality and looks exactly as pictured.',
    name: 'Libby H.',
    country: 'United States',
    rating: 5,
  },
  {
    id: 96,
    text: 'The unicorn phone holder is beautiful. I bought it as a present for my daughter and she loves it! Thanks. Dalia Cintròn Puerto Rico',
    name: 'Dalia V. Cintron',
    country: 'Germany',
    rating: 5,
  },
  {
    id: 97,
    text: 'Soooo nice packging, soooo cute, absolutely perfect to gift to my friend!',
    name: 'Eva',
    country: 'United States',
    rating: 5,
  },
  {
    id: 99,
    text: 'I\'m so in love with this baby, she is so adorable.',
    name: 'Ahna J-Hume',
    country: 'United Kingdom',
    rating: 5,
  },
  {
    id: 101,
    text: 'Second order just as awesome as the first, thank you!',
    name: 'Stephen Parsons',
    country: 'United States',
    rating: 5,
  },
  {
    id: 102,
    text: 'Thanks! this is just as great as the first ones, thank you!',
    name: 'Stephen Parsons',
    country: 'France',
    rating: 5,
  },
  {
    id: 106,
    text: 'I got the 4 leaf clover one and it\'s super cute. Its a little smaller than I expected, but super cute.',
    name: 'Kerri Harris',
    country: 'Netherlands',
    rating: 5,
  },
  {
    id: 107,
    text: 'My friend cried when she opened it; it is so cute!',
    name: 'Alexandra',
    country: 'United States',
    rating: 5,
  },
  {
    id: 108,
    text: 'This beautiful little teacup mermaid is even more stunning in person. I couldn\'t be happier. I am already a repeat customer! ❤',
    name: 'Rachael Shepherd',
    country: 'Australia',
    rating: 5,
  },
  {
    id: 109,
    text: 'Thank you so much! Its the cutest and my boss loved it! Will definitely purchase from you again!',
    name: 'Heather B',
    country: 'United States',
    rating: 5,
  },
  {
    id: 110,
    text: 'I mean, they\'re adorable. love your work! It was worth the wait. Will buy more for sure.',
    name: 'Tracy',
    country: 'Belgium',
    rating: 5,
  },
  {
    id: 114,
    text: 'Perfect for my Family member going thru a tough time!',
    name: 'Leslie Hargraves',
    country: 'Cyprus',
    rating: 5,
  },
  {
    id: 115,
    text: 'Makes me smile every time I look at onmy windowsill!!',
    name: 'Leslie Hargraves',
    country: 'United States',
    rating: 5,
  },
  {
    id: 120,
    text: 'Amazing service! Last was very nice and extremely helpful, I asked many questions and she made me feel at ease! Would definitely recommend x',
    name: 'Emmy',
    country: 'United States',
    rating: 5,
  },
  {
    id: 121,
    text: 'Packaging was perfect and oh my gosh it’s the cutest thing! I got it as a gift for my boyfriend and he loved it. :)',
    name: 'Elizabeth Ware',
    country: 'United Kingdom',
    rating: 5,
  },
  {
    id: 122,
    text: 'Amazing little figurines! Came very quickly, well wrapped as gifts and look really cute! Natalia was also very helpful along the way. Thank you!!!',
    name: 'Kristina K',
    country: 'United States',
    rating: 5,
  },
  {
    id: 123,
    text: 'This is such a cute item!! I gave it to my mother, and she was so happy when she opened the package!!',
    name: 'Bobbi',
    country: 'France',
    rating: 5,
  },
  {
    id: 124,
    text: 'It was even cuter in person! Even though she was in the hospital (I hope she is feeling better!) it arrived in plenty of time! I would definitely order from her again.',
    name: 'Katelyn Koenig',
    country: 'United States',
    rating: 5,
  },
  {
    id: 126,
    text: 'Very happy with purchase of my sleeping mermaid. Thank you.',
    name: 'Sonia',
    country: 'Netherlands',
    rating: 5,
  },
  {
    id: 127,
    text: 'So adorable! All the items came beautifully packaged and are perfect for new year gifts. The seller has been very helpful and I have already placed another order!',
    name: 'Kristina K',
    country: 'United States',
    rating: 5,
  },
  {
    id: 128,
    text: 'These are so adorable and made for a perfect gift!',
    name: 'Abby McCullough',
    country: 'Ireland',
    rating: 5,
  },
  {
    id: 130,
    text: 'All of these miniatures are so cute! I couldn\'t decide which ones to get. Will be ordering more in the future!',
    name: 'Abby McCullough',
    country: 'Ireland',
    rating: 5,
  },
  {
    id: 132,
    text: 'Love her! Thank you so much. Sooo unique and adorable. Thank you also for the beautiful free gift. Received securely packaged. Great working with this shop. Blessed be forever!! Merry Christmas and Happy New Year. Lisa Ferguson',
    name: 'Lisa Ferguson',
    country: 'Australia',
    rating: 5,
  },
  {
    id: 134,
    text: 'These were absolutely beautiful. NatsDoll put together our order quickly and competently, wanted every detail to be perfect, and was great with some minor adjustments we asked for. I really look forward to being just as big a hit at our wedding as they were when I opened the box on delivery!',
    name: 'Jon Paul',
    country: 'United States',
    rating: 5,
  },
  {
    id: 135,
    text: 'quick reply when i had a question and the product is very cute!',
    name: 'Dana',
    country: 'Belgium',
    rating: 5,
  },
  {
    id: 136,
    text: 'The packaging was so adorable and the berry is sooooo adorable ahhhhhh my mom is going to love this',
    name: 'Brittany Morgan',
    country: 'United States',
    rating: 5,
  },
  {
    id: 137,
    text: 'So adorable! I\'m giving it to my best friend for Christmas, and I know she\'ll adore it! So cute!! Thank you! <3',
    name: 'Hannah Armstrong',
    country: 'Cyprus',
    rating: 5,
  },
  {
    id: 138,
    text: 'Cutest little unicorn ever!! Great attention to detail and top quality craftsmanship. Packaged with care and shipped quickly, considering it was an international purchase. Great seller—thank you!!',
    name: 'Beth Linder',
    country: 'United States',
    rating: 5,
  },
  {
    id: 139,
    text: 'Amazing customer service. Made a custom design for me super quick and it came out amazing.',
    name: 'Nina Giangregorio',
    country: 'Germany',
    rating: 5,
  },
  {
    id: 140,
    text: 'FAST shipping. Item as described and pictured. Super cute! Thank you very much!!',
    name: 'Nene',
    country: 'United States',
    rating: 5,
  },
  {
    id: 141,
    text: 'I love this piece. It is obvious the artist put lots of time into her creation. I adore how the ends of the scarf glitter in the light.',
    name: 'Jen Kahn',
    country: 'United Kingdom',
    rating: 5,
  },
  {
    id: 143,
    text: 'She was absolutely amazing to communicate with. Exactly what I wanted for a custom. I would 1000% recommend buying fron her. I am inlove with my purchase',
    name: 'Densiste',
    country: 'Netherlands',
    rating: 5,
  },
  {
    id: 145,
    text: 'These are just the cutest. I ordered one for my daughter and one for me too.',
    name: 'Brenda O\'Borsky',
    country: 'Ireland',
    rating: 5,
  },
  {
    id: 148,
    text: 'CUTE beyond belief. The colours just pop and the little thistle just invokes smiles. Beautiful Nat! As always thank you.',
    name: 'Lina L',
    country: 'France',
    rating: 5,
  },
  {
    id: 149,
    text: 'Love!! Absolutely adorable and amazing little tooth fairy!! Received securely packaged and promptly. Great working with this shop. Can\'t wait to purchase more from this shop. Blessed be forever!! Thank you so much. Kind regards Lisa Ferguson',
    name: 'Lisa Ferguson',
    country: 'United States',
    rating: 5,
  },
  {
    id: 150,
    text: 'It came fast and in a cute gift packaging as I chose this option! My mom loves it, thank you so much :)',
    name: 'Julie Carron',
    country: 'Netherlands',
    rating: 5,
  },
  {
    id: 151,
    text: 'adorable, faster than expected delivery - gift recipient loved it.',
    name: 'Rebecca',
    country: 'United States',
    rating: 5,
  },
  {
    id: 156,
    text: 'He looks exactly like his picture!! This shop is definitely one of my favorites.',
    name: 'Holly Brooke',
    country: 'United States',
    rating: 5,
  },
  {
    id: 157,
    text: 'Exactly what I hoped for. Very cute & real looking. I am very happy with my purchase & will buy again.',
    name: 'Nancy Peters',
    country: 'Germany',
    rating: 5,
  },
  {
    id: 159,
    text: 'The most adorable little gift - so so so cute',
    name: 'Melissa Beaudrie',
    country: 'Belgium',
    rating: 5,
  },
  {
    id: 160,
    text: 'So cute!! I gave this to my sister and she loved it also the seller shipped quickly and everything was packaged very well, will be getting more of these!',
    name: 'Janet Ali',
    country: 'United Arab Emirates',
    rating: 5,
  },
  {
    id: 161,
    text: 'I absolutely love these! Perfect small gifts and the bee is so cute',
    name: 'Janet Ali',
    country: 'United Arab Emirates',
    rating: 5,
  },
  {
    id: 162,
    text: 'Bought as a gift for my younger sister and she loved it, I recommend this store the seller shipped quickly and it makes a wonderful small gift!',
    name: 'Janet Ali',
    country: 'United Arab Emirates',
    rating: 5,
  },
  {
    id: 163,
    text: 'Very cute, brightens up my desk 😁 arrived very quickly too',
    name: 'Emily Savage',
    country: 'United States',
    rating: 5,
  },
  {
    id: 164,
    text: 'This was perfect! Just what I wanted. Seller was super friendly + easy to work with.',
    name: 'Alexis',
    country: 'Cyprus',
    rating: 5,
  },
  {
    id: 165,
    text: 'These are so cute! My work friends found them amusing.',
    name: 'Breanna Shoulders',
    country: 'United States',
    rating: 5,
  },
  {
    id: 167,
    text: 'Got it as a gift for my friend, she loved it!',
    name: 'Birgithe Solstrand',
    country: 'Germany',
    rating: 5,
  },
  {
    id: 168,
    text: 'The first item arrived broken, but the seller very quickly replaced without any extra cost and expedited the shipping. The bean is absolutely adorable. Highly recommended!',
    name: 'Anna Daugherty',
    country: 'United States',
    rating: 5,
  },
  {
    id: 169,
    text: 'The cutest little thing ever! Passed with flying colours as a gift, we both absolutely loved it! Perfectly packaged and made. Thanks a lot!',
    name: 'Soussou',
    country: 'United Kingdom',
    rating: 5,
  },
  {
    id: 171,
    text: 'Super responsive and helped out with a shipping issue immediately! It came super quick after and it was just the cutest thing ever :)',
    name: 'Julia Meyerovich',
    country: 'United States',
    rating: 5,
  },
  {
    id: 172,
    text: 'Реально миниатюрные и очень милые фигурки! Все аккуратно упаковано, приехало в целости и сохранности! Спасибо!',
    name: 'Anastasiia Maksymenko',
    country: 'Russia',
    rating: 5,
  },
  {
    id: 173,
    text: 'Не дождусь, когда смогу подарить это моему директору! Надеюсь он будет в таком же восторге, как и я!',
    name: 'Anastasiia Maksymenko',
    country: 'Russia',
    rating: 5,
  },
  {
    id: 174,
    text: 'Красивая баночка, аккуратная работа и очень приятный продавец! Всем рекомендую!',
    name: 'Anastasiia Maksymenko',
    country: 'Russia',
    rating: 5,
  },
  {
    id: 175,
    text: 'Моя дочь носиться с этой баночкой уже весь вечер! Надеюсь, что эта милая пчёлка и глубокий смысл фразы не оставят никого равнодушными)',
    name: 'Anastasiia Maksymenko',
    country: 'Russia',
    rating: 5,
  },
  {
    id: 176,
    text: 'Все эти нежные, маленькие баночки вызывают умиление. Продавец чуткий и отзывчивый! Крутой подарочек)',
    name: 'Anastasiia Maksymenko',
    country: 'Russia',
    rating: 5,
  },
  {
    id: 177,
    text: 'Наталия, вы вместе с этим занятием сами разносить людям счастье! Побольше вам приятных покупателей! Спасибо большое!',
    name: 'Anastasiia Maksymenko',
    country: 'Russia',
    rating: 5,
  },
  {
    id: 178,
    text: 'Прекрасный сувенир для родных людей! Яркий, как солнышко и на душе от него тоже тепло)',
    name: 'Anastasiia Maksymenko',
    country: 'Russia',
    rating: 5,
  },
  {
    id: 181,
    text: 'Shipped and arrived quicker than expected. Super cute little bottle and I love that they glow in the dark. Would buy from this shop again :)',
    name: 'Grace',
    country: 'France',
    rating: 5,
  },
  {
    id: 182,
    text: 'Shipped and arrived quicker than expected. Super cute cheesy gift, would buy again :)',
    name: 'Grace',
    country: 'United States',
    rating: 5,
  },
  {
    id: 183,
    text: 'I love this! It\'s even cuter than I thought it would be. Can\'t wait to give as a gift.',
    name: 'Stephanie',
    country: 'Netherlands',
    rating: 5,
  },
  {
    id: 184,
    text: 'This is such a fantastic piece of whimsical art. It is so very clever. I could not be happier ❤',
    name: 'Jen Kahn',
    country: 'United States',
    rating: 5,
  },
  {
    id: 185,
    text: 'The wrong item was delivered, and it didn’t include the note I wrote.',
    name: 'Femi',
    country: 'Australia',
    rating: 1,
  },
  {
    id: 186,
    text: 'Blown away by these little figurines! I sent my parents a bunch for their birthdays, and they lit up!! They absolutely loved them. The figurines came so beautifully gift wrapped, and the whole piece - from the faces to the notes to the bottles and ribbons - was perfect. My parents even said "Make sure to leave a wonderful review!". I definitely plan to buy more from this adorable and unique shop.',
    name: 'Amanda',
    country: 'United States',
    rating: 5,
  },
  {
    id: 187,
    text: 'Bought this as a present. Came quick. Was packaged well. So cute in person.',
    name: 'Elizabeth Davis',
    country: 'Belgium',
    rating: 5,
  },
  {
    id: 188,
    text: 'Bought multiple pieces from this artist! So sweet. Fast shipping. The artist is so nice an easy to work with. Will be buying more in the future!',
    name: 'Elizabeth Davis',
    country: 'United States',
    rating: 5,
  },
  {
    id: 189,
    text: 'My favorite piece that I bought from this artist. So stinking cute in person. Just love it.',
    name: 'Elizabeth Davis',
    country: 'Cyprus',
    rating: 5,
  },
  {
    id: 190,
    text: 'Bought this as a stocking stuffer for my husband and can’t wait to give it to him. These r so cute an fun in person!',
    name: 'Elizabeth Davis',
    country: 'United States',
    rating: 5,
  },
  {
    id: 192,
    text: 'Love,love,love. My little unicorn has a wonderful face. She holds the phone easily. But I think she would love to get into mischief',
    name: 'Belinda',
    country: 'Germany',
    rating: 5,
  },
  {
    id: 193,
    text: 'Amazing gift! My girlfriend thought it was the cutest thing 😄',
    name: 'Gustavo',
    country: 'United States',
    rating: 5,
  },
  {
    id: 194,
    text: 'These bees are so adorable!! Highly recommend this shop!! 😊',
    name: 'Jamie Bailey',
    country: 'United Kingdom',
    rating: 5,
  },
  {
    id: 195,
    text: 'A very cute gift for family, friends or co-workers. It arrived quickly and exactly as described. 5 stars!',
    name: 'Kayla',
    country: 'United States',
    rating: 5,
  },
  {
    id: 196,
    text: 'The person I sent it to liked it and it made them smile. The only bad part which I didn’t see anywhere when I ordered it was that it required a signature for delivery... which, for someone who works a 9-5, made it take an extra 10 days and a extra trip to the post office to receive.',
    name: 'Shannon Cribbin',
    country: 'Russia',
    rating: 4,
  },
  {
    id: 197,
    text: 'NatsDolls magical, wonderful, special little dolls will make your heart sing :)',
    name: 'Gayle Wray',
    country: 'France',
    rating: 5,
  },
  {
    id: 198,
    text: 'so so so cute! it was shipped out right away and came quickly even though it was coming from another another country',
    name: 'Hunter Bedard',
    country: 'United States',
    rating: 5,
  },
  {
    id: 201,
    text: 'So freaking cute! Great quality and great unique gift. Love this!',
    name: 'Tonia',
    country: 'Australia',
    rating: 5,
  },
  {
    id: 202,
    text: 'Love Love Love my mermaids. They are unique and beautiful. They shipped fast, and customer service was excellent!',
    name: 'Michelle Thompson',
    country: 'United States',
    rating: 5,
  },
  {
    id: 203,
    text: 'I love this artist’s work! I ordered 3 mermaids from her. They are beautiful. She communicated thoroughly, and shipped quickly. Thank you!',
    name: 'Michelle Thompson',
    country: 'Belgium',
    rating: 5,
  },
  {
    id: 204,
    text: 'Small quirky gift that is well worth the money I would recommend it.',
    name: 'Joe',
    country: 'United States',
    rating: 5,
  },
  {
    id: 205,
    text: 'This was BEYOND perfect . Packaged safe and individually wrapped. Just perfect 💕',
    name: 'Deborah Ramos',
    country: 'Spain',
    rating: 5,
  },
  {
    id: 209,
    text: 'Very well made and incredibly cute! I\'m delighted with them. Thank you so much! 💖',
    name: 'Satin and Tat',
    country: 'Germany',
    rating: 5,
  },
  {
    id: 210,
    text: 'This is soooo cute! I can’t wait to send this to my dear colleague!!!',
    name: 'Katharina Walesch',
    country: 'United States',
    rating: 5,
  },
  {
    id: 211,
    text: 'Bought this for my hubby as a small gift. He laughed :) which is a good thing. We love this little raspberry!',
    name: 'Katharina Walesch',
    country: 'United Kingdom',
    rating: 5,
  },
  {
    id: 212,
    text: 'Fairy house is cute! ❤️ And Natalya was very helpful when i had a query on the tracking status',
    name: 'Rani',
    country: 'United States',
    rating: 5,
  },
  {
    id: 214,
    text: 'Beautiful mermaid necklace. Even shipping internationally it arrived very quickly.',
    name: 'Christina Watson',
    country: 'France',
    rating: 5,
  },
  {
    id: 215,
    text: 'Amazing seller, her items are very sweet and she worked with me to make a great little custom piece. Would come here again!',
    name: 'Bea Evans-Thirlwell',
    country: 'United States',
    rating: 5,
  },
  {
    id: 216,
    text: 'It is absolutely beautiful!! I\'ve been admiring this piece for awhile! I\'m so glad I got one! The quality is amazing! The rice looks real!',
    name: 'Emily Easterly',
    country: 'Netherlands',
    rating: 5,
  },
  {
    id: 217,
    text: 'Love them !! These little bees are just the cutest for some special grad girls.',
    name: 'Michele Delong',
    country: 'United States',
    rating: 5,
  },
  {
    id: 219,
    text: 'I received my luggage safely. It\'s so cute I like it very much. Thank you very much.',
    name: 'Noriko Naganuma',
    country: 'Australia',
    rating: 5,
  },
  {
    id: 221,
    text: 'This little beauty sits on my desk now and I get to enjoy it every day! Came very carefully packaged. I\'ll be happy to buy more from this seller!',
    name: 'Emilie Larson',
    country: 'Belgium',
    rating: 5,
  },
  {
    id: 222,
    text: 'This little creation is pure art. Cute, sweet ,dreaming mermaid. Soft and long pink hair, very well sculpted and detailed. Love her silver tail too. Seller is kind and helpful, she ships fast and is very good in communication. Thank you.',
    name: 'Marialuisa Mandrà',
    country: 'United States',
    rating: 5,
  },
  {
    id: 223,
    text: 'I love strawberries and, while I don\'t normally collect little dolls like this, I totally love this (and I already ordered the chocolate one, too so she has a friend). My items came very carefully packaged - definitely recommend this shop!',
    name: 'Emilie Larson',
    country: 'Cyprus',
    rating: 5,
  },
  {
    id: 224,
    text: 'This is exactly what I needed in my art room - to watch videos while I paint. And it\'s so cute! Love it, thank you!',
    name: 'Emilie Larson',
    country: 'United States',
    rating: 5,
  },
  {
    id: 225,
    text: 'Such an awesome lady! Even put in a free little donut charm with my purchase 😍',
    name: 'Paige Moylan',
    country: 'Germany',
    rating: 5,
  },
  {
    id: 226,
    text: 'Absolutely beautiful and so very full of personality! I am in love with my precious dessert friends.',
    name: 'K Art',
    country: 'United States',
    rating: 5,
  },
  {
    id: 227,
    text: 'What a sweet and lovely little collectible! I ordered 3 little pieces and got them quickly considering the covid stuff & she sent me the most adorable little magnet too as a free gift. I couldn’t be happier.',
    name: 'K Art',
    country: 'United Kingdom',
    rating: 5,
  },
  {
    id: 228,
    text: 'I can’t help it, I am absolutely giddy over these little pieces of precious art. 🍭 I cannot wait to get more items from this seller and I can tell anyone checking reviews, deciding if you should purchase or not, DO IT! 😍 Trust me, these are the cutest little dessert characters I’ve ever seen! I’m hooked on this store. ❤️❤️❤️',
    name: 'K Art',
    country: 'United States',
    rating: 5,
  },
  {
    id: 229,
    text: 'My little penguin is so adorable and even cuter in person!! It makes me so happy!',
    name: 'Melissa Abbott',
    country: 'France',
    rating: 5,
  },
  {
    id: 233,
    text: 'It\'s even cuter in person!! I am so glad I was able to get it!!',
    name: 'Melissa Abbott',
    country: 'Australia',
    rating: 5,
  },
  {
    id: 235,
    text: 'OMG 🥰 l love it. Very cute, very well done with cute details. Lovely job. A real piece of art.I already ordered and have other wonderful things from this store and I plan to even order more. Thank you very much for creating beautiful things !!!!',
    name: 'Norma Rico',
    country: 'Belgium',
    rating: 5,
  },
  {
    id: 236,
    text: 'Lovely work. Well made ; fast, carely packed. Thank you very much for such experience.',
    name: 'Maxime',
    country: 'United States',
    rating: 5,
  },
  {
    id: 240,
    text: 'Tout aussi adorable et finement réalisé !! Je vais pouvoir l\'offrir à Noël grâce à l\'expédition ultra rapide !! Un grand merci je suis RAVIE !!',
    name: 'Ophelie',
    country: 'France',
    rating: 5,
  },
  {
    id: 241,
    text: 'Tellement craquant et adorable, je l\'adore !! Un grand merci à l\'artiste !! En plus le colis est arrivé hyper rapidement et tout était soigneusement emballé dans de très belles boîtes au design personnalisé et précieusement enrubannées !',
    name: 'Ophelie',
    country: 'Germany',
    rating: 5,
  },
  {
    id: 242,
    text: 'Such an adorable pair. Exactly as described if not cuter! Was so lovely to include a beautiful card. Thank you so much!',
    name: 'Lina L',
    country: 'United States',
    rating: 5,
  },
  {
    id: 244,
    text: 'These turned out beautiful :) Made a truly unique gift for my daughters and niece.',
    name: 'Samantha Peaslee',
    country: 'United Kingdom',
    rating: 5,
  },
  {
    id: 245,
    text: 'So sweet and pretty, a wonderful gift to a unicorn lover',
    name: 'Retta',
    country: 'United States',
    rating: 5,
  },
  {
    id: 246,
    text: 'I love it, very sturdy and holds my phone well',
    name: 'Retta',
    country: 'France',
    rating: 5,
  },
  {
    id: 251,
    text: 'Super cute little tea bag holder... perfect for fine bone china mugs or even marking your wine glass! Love him!',
    name: 'Rachel James',
    country: 'United States',
    rating: 5,
  },
  {
    id: 253,
    text: 'I love this piece -- so cute. Arrived well packed. Would definitely buy from this dealer again.',
    name: 'Dorlane Craig',
    country: 'United States',
    rating: 5,
  },
  {
    id: 257,
    text: 'Super cute! I use it at my desk to prop up my phone and watch videos while I work. Great quality!',
    name: 'Danielle Owner FlutterCupDesigns',
    country: 'United States',
    rating: 5,
  },
  {
    id: 258,
    text: 'Just gorgeous. Thank you so much and also thank you for the beautiful free gift. XX',
    name: 'Anna Shannon',
    country: 'Germany',
    rating: 5,
  },
  {
    id: 259,
    text: 'Adorable and fun! Just as pictured. I would definitely purchase again. Thank you for the beautiful gift!',
    name: 'Kaelyn B',
    country: 'United States',
    rating: 5,
  },
  {
    id: 260,
    text: 'Wow so cute! Fast & safe shipping to Australia, thank you!! :)',
    name: 'Melissa',
    country: 'United Kingdom',
    rating: 5,
  },
  {
    id: 261,
    text: 'This is even cuter in person! You are so talented. Love it.',
    name: 'Lauren Michelle',
    country: 'United States',
    rating: 5,
  },
  {
    id: 262,
    text: 'High praise for this ooak doll artist ...My fourth purchase, so glad I found her site!',
    name: 'Luna',
    country: 'France',
    rating: 5,
  },
  {
    id: 263,
    text: 'This cutie has the sweetest expression! Everything Natalya creates is so delicate and pretty.',
    name: 'Luna',
    country: 'United States',
    rating: 5,
  },
  {
    id: 264,
    text: 'Photos don\'t do justice to this darling sushi mermaid ... she\'s absolutely gorgeous!',
    name: 'Luna',
    country: 'Netherlands',
    rating: 5,
  },
  {
    id: 265,
    text: 'My little zucchini doll arrived today and she is lovely :) She was packaged beautifully in a gift box and protected well so she arrived undamaged :) She even came with a sweet unicorn brooch as a gift. Highly recommended ❤',
    name: 'Rachel James',
    country: 'United States',
    rating: 5,
  },
  {
    id: 266,
    text: 'LOVE IT! So cute and well made! Arrived safe, and in a cute box. Will definitely order again!',
    name: 'Karolin Rantala',
    country: 'Australia',
    rating: 5,
  },
  {
    id: 267,
    text: 'LOVE this piece! So excited to give to my pregnant friend who has had a very hard pregnancy. Seller was great, and shipped it our quickly. Also included a beautiful gift. Thank you so much!',
    name: 'Katya Herb',
    country: 'United States',
    rating: 5,
  },
  {
    id: 268,
    text: 'I love this doll. She is more beautiful then in the photos. I have ordered several of Nat\'s dolls, and she is my favorite. The colors are so vibrant, and her hair is amazing. The shipping time was very quick. Just over a week. Thank you for the adorable gift. I love this shop!!!',
    name: 'Lia',
    country: 'Belgium',
    rating: 5,
  },
  {
    id: 269,
    text: 'I love this little sushi mermaid so much ... She is adorable! And she came in a cute box with a special extra gift, which I appreciate very much. Excellent artist with excellent service!',
    name: 'Luna',
    country: 'United States',
    rating: 5,
  },
  {
    id: 270,
    text: 'She is beautiful. Her tail was broke, but I glued it back on. Love your work 💕💕',
    name: 'Angel Soto',
    country: 'Spain',
    rating: 5,
  },
  {
    id: 271,
    text: 'What a cute concept!! We love this little sushi mermaid!',
    name: 'Ariel',
    country: 'Cyprus',
    rating: 5,
  },
  {
    id: 272,
    text: 'This is adorable and arrived safely from overseas! Thanks so much!',
    name: 'Ariel',
    country: 'United States',
    rating: 5,
  },
  {
    id: 274,
    text: 'What an adorable fairy house. Love it! Thank you so much!',
    name: 'Darlene Murray',
    country: 'Ireland',
    rating: 5,
  },
  {
    id: 276,
    text: 'This is so cute and very well made. I am more than happy! Looks just like the picture.',
    name: 'Kelley Kokes',
    country: 'Germany',
    rating: 5,
  },
  {
    id: 277,
    text: 'Beautiful!!! Much larger than I expected!!! Love her!!! She\'s perfect for my fairy garden! Highly recommend!!!',
    name: 'Nancy Acosta',
    country: 'Spain',
    rating: 5,
  },
  {
    id: 278,
    text: 'Product arrived safely. Thank you for your concern. Thank you for the present! I liked it very much.',
    name: 'Noriko Naganuma',
    country: 'United States',
    rating: 5,
  },
  {
    id: 279,
    text: 'So very cute. I can\'t wait to wear it. Thank you!',
    name: 'Heather Renee',
    country: 'United Kingdom',
    rating: 5,
  },
  {
    id: 281,
    text: 'I can not wait for it to be Christmas day! I purchased this beautiful necklace for my daughter and Nat added in a bonus panda knowing that my daughter loves pandas!!! Thank you so much. I will recommend you always and have plans on future purchases 💙',
    name: 'Kayla Calix-Hestick',
    country: 'France',
    rating: 5,
  },
  {
    id: 282,
    text: 'Adorable, she will make a great addition to my mermaid collection.',
    name: 'Retta',
    country: 'United States',
    rating: 5,
  },
  {
    id: 286,
    text: 'Product arrived safely.This is very cute.Thank you for your rapid shipment.',
    name: 'Noriko Naganuma',
    country: 'United States',
    rating: 5,
  },
  {
    id: 287,
    text: 'Product arrived safely.This is very cute.Thank you for your rapid shipment.This girl is my second mermaid.Lovely.',
    name: 'Noriko Naganuma',
    country: 'Belgium',
    rating: 5,
  },
  {
    id: 288,
    text: 'Love it, purchased as a gift for a little girl, thank you for making it a necklace. Thought it was just going to be the charm.',
    name: 'Olga Flores',
    country: 'Spain',
    rating: 5,
  },
  {
    id: 289,
    text: 'She is just beautiful and is as described. Fast shipping too. Thank you!',
    name: 'Antionette Kruger',
    country: 'United States',
    rating: 5,
  },
  {
    id: 291,
    text: 'Absolutely stunning doll, my almost 5 years old daughter thought it\'s a real mermaid and asked me when she is going to wake-up. We are planning a mermaid themed Birthday party for my little one and we going to use this beautiful doll as a cake topper. I also would like to say thank you to shop for fast delivery.',
    name: 'Peony Blossom',
    country: 'Cyprus',
    rating: 5,
  },
  {
    id: 292,
    text: 'My new favorite necklace! I got this for myself for my birthday and I love it! Great quality, amazing price, and fast shipping!',
    name: 'Robyn Blake',
    country: 'United States',
    rating: 5,
  },
  {
    id: 293,
    text: 'She is a beautiful sleeping clay mermaid. I am very happy with my purchase. Thank you.',
    name: 'Sonia',
    country: 'Germany',
    rating: 5,
  },
  {
    id: 295,
    text: 'Adorable!!! The artist is amazing!!! Got here in 2 weeks to Texas. Package was well protected to prevent being hurt. Thanks so much 🐼❤',
    name: 'Cassandra Earley',
    country: 'United Kingdom',
    rating: 5,
  },
  {
    id: 297,
    text: 'Love this little mermaid, she is so cute and well made and the details are adorable. She is the perfect size for a terrarium and the shop owner is so helpful and nice!',
    name: 'Claire Allen',
    country: 'France',
    rating: 5,
  },
  {
    id: 298,
    text: 'Very happy with the Ooak sculpted clay sleeping mermaid doll. Thank you.',
    name: 'Sonia',
    country: 'United States',
    rating: 5,
  },
  {
    id: 299,
    text: 'I love this Alice In Wonderland necklace. The artist is very talented and the details are amazing. My order was well packed and shipped fast.',
    name: 'Ginny',
    country: 'Netherlands',
    rating: 5,
  },
  {
    id: 301,
    text: 'So beautiful I Truely love her work! She Anamazing artist ! I will order more soon!!!',
    name: 'Michelle hinds',
    country: 'Australia',
    rating: 5,
  },
  {
    id: 302,
    text: 'She is sooooooo cute! She is wearing a necklace,it\'s so small and cute. Package is cute too.I was very impressed. Thank you, "NatsDoll"',
    name: 'Noriko Naganuma',
    country: 'United States',
    rating: 5,
  },
  {
    id: 303,
    text: 'I love it. I tried to upload a photo but the app wasn\'t working right. This is the cutest thing ever. My phone fits perfectly. Great item for the price. I will shop again.',
    name: 'Rebecca Epp TheSteampunkBuddha',
    country: 'Belgium',
    rating: 5,
  },
  {
    id: 305,
    text: 'Very funny pigs family. My daughter loved them from the first sight. You just invent every time new story about them, and your child will be surprised each time and happy to hear (and see) about adventures of this funny family. Characters are very detailed and look very close to the original ones from the cartoon. Thanks a lot Natalia for such an great work',
    name: 'Estibela',
    country: 'United States',
    rating: 5,
  },
  {
    id: 307,
    text: 'So pleased with my pendant. The attention to detail <3 Thank you to Natalya~ the communication between shop owner and customer is top notch!! I will definitely be ordering from this shop again.',
    name: 'Brekke',
    country: 'United States',
    rating: 5,
  },
  {
    id: 308,
    text: 'Very cute! Plan to give as a gift and I think she\'ll love it.',
    name: 'Jamie',
    country: 'Germany',
    rating: 5,
  },
  {
    id: 310,
    text: 'I received the clay sitting mermaid on November 21, 2017. She is a beautiful clay mermaid. Thank you.',
    name: 'Sonia',
    country: 'United States',
    rating: 5,
  },
  {
    id: 313,
    text: 'I was refunded due to post losing my order. Thank you Nat for my refund. Let’s hope it gets found. X',
    name: 'Lilyana',
    country: 'France',
    rating: 5,
  },
  {
    id: 316,
    text: 'Thank you nat :) she is so pretty. Will be shopping with you again. Thank you for a quick delivery too.',
    name: 'Lilyana',
    country: 'Netherlands',
    rating: 5,
  },
  {
    id: 317,
    text: 'Love this gorgeous little doll... Well made and quickly shipped - thank you!',
    name: 'Anne Hampton',
    country: 'United States',
    rating: 5,
  },
  {
    id: 319,
    text: 'One of two Mermaid pendants I ordered for myself, 54 years young! They are so cute and fun, I can\'t wait to wear them! I live in Florida, and I\'m sure these will draw a lot of attention and compliments. They arrived well packaged in a cute little illustrated box with a pink ribbon. Great purchase and prompt delivery. Thank you!!',
    name: 'Jamie Logan',
    country: 'United States',
    rating: 5,
  },
  {
    id: 320,
    text: 'Sooo cute!! Ordered two of these pendants. You don\'t need to be a kid, just young at heart, to appreciate these adorable pendants. Very detailed, and full of personality. Thanks for a wonderful purchase!!',
    name: 'Jamie Logan',
    country: 'Belgium',
    rating: 5,
  },
  {
    id: 321,
    text: 'Beautifully detailed design, you can see the love of the artist in making this pendant. THANK YOU!',
    name: 'Mina Saberi',
    country: 'United States',
    rating: 5,
  },
  {
    id: 322,
    text: 'My niece loved this doll. Great quality and will buy again, thank you!!',
    name: 'Judy Graham',
    country: 'Cyprus',
    rating: 5,
  },
  {
    id: 323,
    text: 'Absolutely beautiful... exactly as described and the service was amazing!',
    name: 'Amelia Caceres',
    country: 'United States',
    rating: 5,
  },
  {
    id: 325,
    text: 'The doll is absolutely cute! Great seller and artist, I love it :)',
    name: 'Karina Łagowska',
    country: 'Poland',
    rating: 5,
  },
  {
    id: 329,
    text: 'She is absolutely precious!! Definately worth the wait!!! Need to get her a chair!! Thank you so much!',
    name: 'Yadira Dale',
    country: 'United States',
    rating: 5,
  },
  {
    id: 330,
    text: 'This doll is just fabulous!! I love it! And I get the humor on that generous gift! :O) Thank you so much!!',
    name: 'Izzypoopah',
    country: 'United Kingdom',
    rating: 5,
  },
  {
    id: 331,
    text: 'Just adorable! Perfect addition to my daughter\'s angel collection! Thank you!!!!!',
    name: 'Melissa MacLeod Needlepoint',
    country: 'United States',
    rating: 5,
  },
  {
    id: 332,
    text: 'I am 48 and I want one for MYSELF!!!!!! This little mermaid is TOOOOO CUTE!!!!!!!!! perfect ...',
    name: 'Angela Birdsong',
    country: 'France',
    rating: 5,
  },
  {
    id: 333,
    text: 'My GROWN daughter will love this!!!!!!!!! I am still amazed how someone can do this with clay..SO detailed... a true art!!!',
    name: 'Angela Birdsong',
    country: 'United States',
    rating: 5,
  },
  {
    id: 334,
    text: 'Beautiful little doll, and such a lovely face! Thank you for fast delivery too!',
    name: 'Shay',
    country: 'Netherlands',
    rating: 5,
  },
  {
    id: 337,
    text: 'Beautiful!! Very well-made custom order doll! I just love the way that red dress turned out and the hair is perfect color. The boy doll looks so adorable! Meticulously packaged, thanks so much - and for that unexpected gift, too! :)',
    name: 'Izzypoopah',
    country: 'United States',
    rating: 5,
  },
  {
    id: 339,
    text: 'You make very beautiful dolls!! It\'s exactly as pictured. Carefully packed. I probably would buy again! :)',
    name: 'Izzypoopah',
    country: 'Australia',
    rating: 5,
  },
  {
    id: 340,
    text: 'Your dolls are just gorgeous!! - from the face to the hair and even the clothes. I felt like a child again when as I was opening the package! They\'re very much worth it, thanks!',
    name: 'Izzypoopah',
    country: 'United States',
    rating: 5,
  },
  {
    id: 341,
    text: 'Handcrafted to perfection, I sent her a picture and she made it look as if my daughter was dancing irish dance. Thank you!',
    name: 'Steph Matus',
    country: 'Belgium',
    rating: 5,
  },
  {
    id: 343,
    text: 'lovely!!! really nice item for gift. Fast shipping. Thank you!',
    name: 'Daniela Palatnik',
    country: 'United States',
    rating: 5,
  },
  {
    id: 344,
    text: 'I love her. She is so cool. She looks great in my curio cabinet. Thanks for the great work.',
    name: 'Christine Greenwood',
    country: 'Cyprus',
    rating: 5,
  },
  {
    id: 345,
    text: 'iBeautiful doll,,handmade and just lovely,Came with props..wonderful artist,FAST Shipping Careful packing,Wonderful seller,Thankyou',
    name: 'Bonita Walker',
    country: 'United States',
    rating: 5,
  },
  {
    id: 349,
    text: 'The seller was great to work with. She responded quickly to my questions. She even sent me pictures of my item before shipping it to get my approval. The doll is adorable and my daughter loves it. I think I will be buying from this shop again. It took about 2 weeks to get my doll but it\'s international shipping so that\'s understandable.',
    name: 'Ana Gualan',
    country: 'United States',
    rating: 5,
  },
  {
    id: 351,
    text: 'This is an adorable little doll. She\'s well-made and just so cute!',
    name: 'Amanda Childs',
    country: 'United Kingdom',
    rating: 5,
  },
  {
    id: 352,
    text: 'This is a sweet little doll. She\'s well-made and super cute!',
    name: 'Amanda Childs',
    country: 'United States',
    rating: 5,
  },
  {
    id: 353,
    text: 'beautiful craftsmanship, perfect size, amazing attention to detail, so unique and charming!',
    name: 'Dawn Frederickson',
    country: 'France',
    rating: 5,
  },
  {
    id: 354,
    text: 'What a great little doll, thank you for being so talented, and for sharing that talent!',
    name: 'Shay',
    country: 'United States',
    rating: 5,
  },
  {
    id: 356,
    text: 'I love her dolls. they have a winsome look about them. I\'m not looking to duplicate her dolls but love getting tips and ideas for making the most of the dolls I make. I have her other pattern and this one looks to be filled with good tips and techniques.',
    name: 'JDFabricCreations',
    country: 'United States',
    rating: 5,
  },
  {
    id: 357,
    text: 'This is a very well made, detailed and adorable doll. Thank you!',
    name: 'Darlene Dunn',
    country: 'Australia',
    rating: 5,
  },
  {
    id: 360,
    text: 'I\'m always looking for new information on how to make better doll faces. I like her dolls and the eyes especially so I thought this would help me. Has lots of good pictures.',
    name: 'JDFabricCreations',
    country: 'Belgium',
    rating: 5,
  },
  {
    id: 361,
    text: 'It is a beautiful doll, and worth the wait of 2 months to ship from Russia.',
    name: 'Lisa Molitor',
    country: 'United States',
    rating: 5,
  },
  {
    id: 363,
    text: 'The doll was gorgeous and arrived quickly. Thank you! It made a wonderful gift!',
    name: 'Anna Rosanova',
    country: 'Russia',
    rating: 5,
  },
  {
    id: 365,
    text: 'Beautiful doll, I love all the little details, so well made and shipped so fast. Thank you.',
    name: 'Stefania Brunoni',
    country: 'Cyprus',
    rating: 5,
  },
  {
    id: 366,
    text: 'Sweet doll! A real treat to make and dress. The pattern is easy to follow, and lends itself to many eras with a change of wardrobe and hair style.',
    name: 'Cheryl Houck',
    country: 'United States',
    rating: 5,
  },
  {
    id: 367,
    text: 'Well explained and shown clearly with pictures. These dolls do look cute and unique and have very expressive eyes and face. Thanks.',
    name: 'Mirayan',
    country: 'Germany',
    rating: 5,
  },
  {
    id: 368,
    text: 'While the description did state that there are no sewing directions I did not expect there to be absolutely no instructions.',
    name: 'Lisa Wright',
    country: 'United States',
    rating: 2,
  },
  {
    id: 374,
    text: 'I love my mini baby!!! I am naming her Samatha!!',
    name: 'Martinique Gilchrist',
    country: 'United States',
    rating: 5,
  },
  {
    id: 375,
    text: 'She is beautiful! Can\'t wait to make her! thank you',
    name: 'Mary Kay Montague',
    country: 'France',
    rating: 5,
  },
  {
    id: 376,
    text: 'beautiful doll...just arrived...love her! she is exactly like the listing. high quality, very happy :)',
    name: 'Esther F. Gorden',
    country: 'United States',
    rating: 5,
  },
  {
    id: 380,
    text: 'I had a great time making this doll for a friend! I think I will make another one soon! Thank you Nat for all your help when I had questions!',
    name: 'Christina Little',
    country: 'Netherlands',
    rating: 5,
  },
  {
    id: 383,
    text: 'Dankeschön,tolle genaue Anleitung,EMPFEHLENSWERT !!! leider ohne Schnittmuster für Bekleidung.Trotzdem 5 Sterne !!!',
    name: 'Petra Sell',
    country: 'Germany',
    rating: 5,
  },
  {
    id: 384,
    text: 'beautiful doll and pattern. i love the instant download. Thank you!',
    name: 'Sonia Young',
    country: 'Belgium',
    rating: 5,
  },
  {
    id: 388,
    text: 'Yesss! I\'m finally got my dolls! Natalya\'s dolls are absolutely wonderful, adorable and cute! All details are made very accurate. Thanks a lot!',
    name: 'White Giraffe',
    country: 'Cyprus',
    rating: 5,
  },
  {
    id: 389,
    text: 'very nice and easy pattern! Can\'t wait to finish it!!',
    name: 'CK Garred',
    country: 'United States',
    rating: 4,
  },
  {
    id: 392,
    text: 'Thank you for sharing your patterns! They are so lovely, my girls love them!',
    name: 'Andrea Geldart',
    country: 'United Kingdom',
    rating: 5,
  },
  {
    id: 395,
    text: 'OMG, these dolls are so adorable!! Thank you so much!',
    name: 'Andrea Geldart',
    country: 'United States',
    rating: 5,
  },
  {
    id: 396,
    text: 'OMG, these dolls are so adorable!! Thank you so much! My daughters love them! And thank you for the giraffe! Absolutely adorable and fantastic quality!',
    name: 'Andrea Geldart',
    country: 'Netherlands',
    rating: 5,
  },
  {
    id: 398,
    text: 'Thanks! They are so well-made and just so pretty to look at.',
    name: 'Julia Semenko',
    country: 'Russia',
    rating: 5,
  },
  {
    id: 401,
    text: 'One of the clearest patterns and instructions ever! nThanks a million!',
    name: 'Mireille Both',
    country: 'United States',
    rating: 5,
  },
  {
    id: 403,
    text: 'A great compliment to a woman selling exquisite politeness, honesty and skill: the pattern of the dolls that I purchased is beautiful and very well explained step by step. And it came in a moment. Thanks Nata, a big kiss',
    name: 'Moise Mariana',
    country: 'United States',
    rating: 5,
  },
  {
    id: 404,
    text: 'A wonderful person! Very reliable, kind and super helpful! Impeccable seller! Thank you for everything!',
    name: 'Moise Mariana',
    country: 'Cyprus',
    rating: 5,
  },
  {
    id: 405,
    text: 'Hello Natalya. Your sweet girl arrived safely and when expected. My feedback is tardy. She is so lovely and unusual. Thank you.',
    name: 'Beatriz del Barco',
    country: 'United States',
    rating: 5,
  },
  {
    id: 408,
    text: 'Thank you so much for a wonderful doll!! She is perfect thank you.',
    name: 'Sarah Nguyen',
    country: 'France',
    rating: 5,
  },
]